name: Job Bot Workforce - Run every 10 min

on:
  schedule:
    - cron: '*/10 * * * *' # toutes les 10 minutes
  workflow_dispatch: # permet de lancer manuellement depuis GitHub si besoin

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node index.js
